### PR TITLE
Use oc cp instead of implementing it, bump k8s libs

### PR DESCRIPTION
**Pull request by jhrozek**
- Use oc cp instead of implementing our version of Ccp
- Bump k8s.io/kubectl from 0.24.4 to 0.26.1

### CODE REVIEW

**Comment by xiaojiey** [comment]
Verified with 4.13 nightly payload 4.13.0-0.nightly-2023-02-03-145213 + code in the PR:
The only problem is: it run into below error very easily. Not sure if possible to improve.
@jhrozek , any comments? Thanks.
 **Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF
, err: exit status 1**
```
$ make 
go build -o ./bin/oc-compliance ./cmd ;
$ ./bin/oc-compliance  bind -N test1 -S default profile/ocp4-cis profile/ocp4-cis-node
Creating ScanSettingBinding test1
[xiyuan@MiWiFi-RA69-srv oc-compliance (pr-226)]$ oc get ssb
NAME    AGE
test    97m
test1   9s
$ oc get suite test1
NAME    PHASE     RESULT
test1   RUNNING   NOT-AVAILABLE
test1   RUNNING   NOT-AVAILABLE
test1   AGGREGATING   NOT-AVAILABLE
test1   AGGREGATING   NOT-AVAILABLE
test1   DONE          INCONSISTENT
test1   DONE          INCONSISTENT
$ ./bin/oc-compliance  fetch-raw scansettingbinding test1 -o resultsdir/
Fetching results for test1 scans: ocp4-cis, ocp4-cis-node-master, ocp4-cis-node-worker
W0206 23:02:32.458644  149547 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-mgk6w'.Fetching raw compliance results for scan 'ocp4-cis'..
**Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF
, err: exit status 1**
$ ./bin/oc-compliance  fetch-raw scansettingbinding test1 -o resultsdir/
Fetching results for test1 scans: ocp4-cis, ocp4-cis-node-master, ocp4-cis-node-worker
Error: Unable to create directory resultsdir/ocp4-cis: mkdir resultsdir/ocp4-cis: file exists
$ rm -rf resultsdir
$ ./bin/oc-compliance  fetch-raw scansettingbinding test1 -o resultsdir/
Error: The directory at path 'resultsdir/' doesn't exist
[xiyuan@MiWiFi-RA69-srv oc-compliance (pr-226)]$ mkdir resultsdir
$ ./bin/oc-compliance  fetch-raw scansettingbinding test1 -o resultsdir/
Fetching results for test1 scans: ocp4-cis, ocp4-cis-node-master, ocp4-cis-node-worker
W0206 23:03:22.415432  149672 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-c9hxh'.Fetching raw compliance results for scan 'ocp4-cis'..
**Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF
, err: exit status 1**
$ ./bin/oc-compliance  fetch-raw compliancesuite test1 -o resultsdir/
Fetching results for test1 scans: ocp4-cis, ocp4-cis-node-master, ocp4-cis-node-worker
W0206 23:05:04.065041  149897 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-gg6cl'.Fetching raw compliance results for scan 'ocp4-cis'..
The raw compliance results are avaliable in the following directory: resultsdir/ocp4-cis
W0206 23:05:15.978891  149897 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-z958k'.Fetching raw compliance results for scan 'ocp4-cis-node-master'......
The raw compliance results are avaliable in the following directory: resultsdir/ocp4-cis-node-master
W0206 23:05:54.378478  149897 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-njb96'.Fetching raw compliance results for scan 'ocp4-cis-node-worker'........
**Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF
, err: exit status 1**
$ cd resultsdir/
$ ls -ltr ocp4-cis-node-master/
total 780
-rw-r--r--. 1 xiyuan xiyuan 263547 Feb  6 23:05 openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml.bzip2
-rw-r--r--. 1 xiyuan xiyuan 263497 Feb  6 23:05 openscap-pod-548e3c633f23190391ca0e6918df967bb816b4a1.xml.bzip2
-rw-r--r--. 1 xiyuan xiyuan 263514 Feb  6 23:05 openscap-pod-765ea3c7a82503f5dd6506795c6a3d511b132dbf.xml.bzip2
$ bunzip2 -c ocp4-cis-node-master/openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml.bzip2 > openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml
$ file openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml
openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml: XML 1.0 document, Unicode text, UTF-8 text, with very long lines (970)
[xiyuan@MiWiFi-RA69-srv resultsdir (pr-226)]$ head openscap-pod-dfd2646981bd5254080f2c20f0c5507d547359cb.xml
<?xml version="1.0" encoding="UTF-8"?>
<arf:asset-report-collection xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" xmlns:core="http://scap.nist.gov/schema/reporting-core/1.1" xmlns:ai="http://scap.nist.gov/schema/asset-identification/1.1">
  <core:relationships xmlns:arfvocab="http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0#">
    <core:relationship type="arfvocab:createdFor" subject="xccdf1">
      <core:ref>collection1</core:ref>
    </core:relationship>
    <core:relationship type="arfvocab:isAbout" subject="xccdf1">
      <core:ref>asset0</core:ref>
    </core:relationship>
  </core:relationships>
$ bunzip2 -c ocp4-cis/ocp4-cis-api-checks-pod.xml.bzip2 > ocp4-cis-api-checks-pod.xml
$ file ocp4-cis-api-checks-pod.xml 
ocp4-cis-api-checks-pod.xml: XML 1.0 document, Unicode text, UTF-8 text, with very long lines (970)
$ head ocp4-cis-api-checks-pod.xml
<?xml version="1.0" encoding="UTF-8"?>
<arf:asset-report-collection xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" xmlns:core="http://scap.nist.gov/schema/reporting-core/1.1" xmlns:ai="http://scap.nist.gov/schema/asset-identification/1.1">
  <core:relationships xmlns:arfvocab="http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0#">
    <core:relationship type="arfvocab:createdFor" subject="xccdf1">
      <core:ref>collection1</core:ref>
    </core:relationship>
    <core:relationship type="arfvocab:isAbout" subject="xccdf1">
      <core:ref>asset0</core:ref>
    </core:relationship>
  </core:relationships>
```

**Comment by BhargaviGudi** [comment]
Verification with 4.13.0-0.nightly-2023-02-03-145213
Compliance bundle v0.1.60
```
[bgudi@bgudi oc-compliance]$ oc get ssb -n openshift-compliance 
NAME    AGE
test    117m
test1   20m
[bgudi@bgudi oc-compliance]$ oc get suite -n openshift-compliance 
NAME    PHASE   RESULT
test    DONE    NON-COMPLIANT
test1   DONE    INCONSISTENT
[bgudi@bgudi oc-compliance]$ oc get ssb -n openshift-compliance 
NAME    AGE
test    118m
test1   20m
[bgudi@bgudi oc-compliance]$ oc get pods -n openshift-compliance 
NAME                                              READY   STATUS    RESTARTS        AGE
compliance-operator-fb7bb6f5f-wxdrz               1/1     Running   1 (3h22m ago)   3h23m
ocp4-openshift-compliance-pp-86c767b5b8-87bmj     1/1     Running   0               3h22m
raw-result-extractor-86lkl                        1/1     Running   0               81m
raw-result-extractor-c9hxh                        1/1     Running   0               17m
raw-result-extractor-mgk6w                        1/1     Running   0               17m
raw-result-extractor-njb96                        1/1     Running   0               14m
rhcos4-openshift-compliance-pp-844989b8c4-dz878   1/1     Running   0               3h22m
[bgudi@bgudi oc-compliance]$ make
go build -o ./bin/oc-compliance ./cmd
[bgudi@bgudi oc-compliance]$ ./bin/oc-compliance fetch-raw scansettingbinding test -o /tmp/
Fetching results for test scans: ocp4-cis
Error: Unable to create directory /tmp/ocp4-cis: mkdir /tmp/ocp4-cis: file exists
[bgudi@bgudi oc-compliance]$ rm -rf /tmp/ocp4-cis
[bgudi@bgudi oc-compliance]$ ./bin/oc-compliance fetch-raw scansettingbinding test -o /tmp/
Fetching results for test scans: ocp4-cis
W0206 20:54:53.950773  595988 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-hh2xw'.Fetching raw compliance results for scan 'ocp4-cis'..
The raw compliance results are avaliable in the following directory: /tmp/ocp4-cis
[bgudi@bgudi oc-compliance]$ cd /tmp/ocp4-cis
[bgudi@bgudi ocp4-cis]$ ls -ltr
total 448
-rw-rw-r--. 1 bgudi bgudi 278359 Feb  6 20:55 ocp4-cis-api-checks-pod.xml.bzip2
[bgudi@bgudi ocp4-cis]$ bzip2 -dk ocp4-cis-api-checks-pod.xml.bzip2
bzip2: Can't guess original name for ocp4-cis-api-checks-pod.xml.bzip2 -- using ocp4-cis-api-checks-pod.xml.bzip2.out
[bgudi@bgudi ocp4-cis]$ ls -ltr
total 6800
-rw-rw-r--. 1 bgudi bgudi 6500898 Feb  6 20:55 ocp4-cis-api-checks-pod.xml.bzip2.out
-rw-rw-r--. 1 bgudi bgudi  278359 Feb  6 20:55 ocp4-cis-api-checks-pod.xml.bzip2
[bgudi@bgudi ocp4-cis]$ vi ocp4-cis-api-checks-pod.xml.bzip2.out
[bgudi@bgudi ocp4-cis]$ head ocp4-cis-api-checks-pod.xml.bzip2.out
<?xml version="1.0" encoding="UTF-8"?>
<arf:asset-report-collection xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" xmlns:core="http://scap.nist.gov/schema/reporting-core/1.1" xmlns:ai="http://scap.nist.gov/schema/asset-identification/1.1">
  <core:relationships xmlns:arfvocab="http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0#">
    <core:relationship type="arfvocab:createdFor" subject="xccdf1">
      <core:ref>collection1</core:ref>
    </core:relationship>
    <core:relationship type="arfvocab:isAbout" subject="xccdf1">
      <core:ref>asset0</core:ref>
    </core:relationship>
  </core:relationships>
[bgudi@bgudi ocp4-cis]$ ls
ocp4-cis-api-checks-pod.xml.bzip2  ocp4-cis-api-checks-pod.xml.bzip2.out
[bgudi@bgudi ocp4-cis]$ file ocp4-cis-api-checks-pod.xml.bzip2.out
ocp4-cis-api-checks-pod.xml.bzip2.out: XML 1.0 document, UTF-8 Unicode text, with very long lines
[bgudi@bgudi ocp4-cis]$ cd -
/home/bgudi/goLang/work/src/github.com/openshift/oc-compliance
[bgudi@bgudi oc-compliance]$ oc get suite
NAME    PHASE   RESULT
test    DONE    NON-COMPLIANT
test1   DONE    INCONSISTENT
[bgudi@bgudi oc-compliance]$ ./bin/oc-compliance fetch-raw compliancesuite test -o /tmp/
Fetching results for test scans: ocp4-cis
Error: Unable to create directory /tmp/ocp4-cis: mkdir /tmp/ocp4-cis: file exists
[bgudi@bgudi oc-compliance]$ rm -rf /tmp/ocp4-cis
[bgudi@bgudi oc-compliance]$ ./bin/oc-compliance fetch-raw compliancesuite test -o /tmp/
Fetching results for test scans: ocp4-cis
W0206 20:59:12.759208  596974 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-extract-pod" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-extract-pod" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "pv-extract-pod" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "pv-extract-pod" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Fetching raw compliance results for pod 'raw-result-extractor-86gtz'.Fetching raw compliance results for scan 'ocp4-cis'..
The raw compliance results are avaliable in the following directory: /tmp/ocp4-cis
[bgudi@bgudi oc-compliance]$ cd /tmp/ocp4-cis
[bgudi@bgudi ocp4-cis]$ ls
ocp4-cis-api-checks-pod.xml.bzip2
[bgudi@bgudi ocp4-cis]$ bzip2 ocp4-cis-api-checks-pod.xml.bzip2 
[bgudi@bgudi ocp4-cis]$ ls -ltr
total 256
-rw-rw-r--. 1 bgudi bgudi 260412 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2.bz2
[bgudi@bgudi ocp4-cis]$ ls -ltr
total 528
-rw-rw-r--. 1 bgudi bgudi 260412 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2.bz2
-rw-rw-r--. 1 bgudi bgudi 278359 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2
[bgudi@bgudi ocp4-cis]$ bzip2 -dk ocp4-cis-api-checks-pod.xml.bzip2
bzip2: Can't guess original name for ocp4-cis-api-checks-pod.xml.bzip2 -- using ocp4-cis-api-checks-pod.xml.bzip2.out
[bgudi@bgudi ocp4-cis]$ ls -ltr
total 6880
-rw-rw-r--. 1 bgudi bgudi 6500898 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2.out
-rw-rw-r--. 1 bgudi bgudi  260412 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2.bz2
-rw-rw-r--. 1 bgudi bgudi  278359 Feb  6 20:59 ocp4-cis-api-checks-pod.xml.bzip2
[bgudi@bgudi ocp4-cis]$ head ocp4-cis-api-checks-pod.xml.bzip2.out
<?xml version="1.0" encoding="UTF-8"?>
<arf:asset-report-collection xmlns:arf="http://scap.nist.gov/schema/asset-reporting-format/1.1" xmlns:core="http://scap.nist.gov/schema/reporting-core/1.1" xmlns:ai="http://scap.nist.gov/schema/asset-identification/1.1">
  <core:relationships xmlns:arfvocab="http://scap.nist.gov/specifications/arf/vocabulary/relationships/1.0#">
    <core:relationship type="arfvocab:createdFor" subject="xccdf1">
      <core:ref>collection1</core:ref>
    </core:relationship>
    <core:relationship type="arfvocab:isAbout" subject="xccdf1">
      <core:ref>asset0</core:ref>
    </core:relationship>
  </core:relationships>
[bgudi@bgudi ocp4-cis]$ file ocp4-cis-api-checks-pod.xml.bzip2.out
ocp4-cis-api-checks-pod.xml.bzip2.out: XML 1.0 document, UTF-8 Unicode text, with very long lines
```

**Comment by jhrozek** [comment]
> Verified with 4.13 nightly payload 4.13.0-0.nightly-2023-02-03-145213 + code in the PR:
> The only problem is: it run into below error very easily. Not sure if possible to improve.
> @jhrozek , any comments? Thanks.
> **Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF , err: exit status 1**

And the same report on the same machine with the original version works? This really sounds like an env. issue ...

**Comment by xiaojiey** [comment]
Maybe

> > Verified with 4.13 nightly payload 4.13.0-0.nightly-2023-02-03-145213 + code in the PR:
> > The only problem is: it run into below error very easily. Not sure if possible to improve.
> > @jhrozek , any comments? Thanks.
> > **Error: Unable to process results from suite test1: the cp command failed with: error: unexpected EOF , err: exit status 1**
> 
> And the same report on the same machine with the original version works? This really sounds like an env. issue ...
Should be an env issue. I rerun it today. I didn't run into the EOF issue today. Will continue monitoring issue whether it will reproduce again or not.

**Comment by rhmdnd** [comment]
Worked through an alternative approach that uses `Complete()` instead of `Run()` to set the arguments.

https://github.com/openshift/oc-compliance/pull/227

**Comment by jhrozek** [comment]
Superseded by https://github.com/openshift/oc-compliance/pull/227

**Pull request closed without merging**
